---

- name: ansible playbook
  hosts: '{{ hosts }}'
  # gather_facts: false
  remote_user: root
  # become: yes
  vars:
    user_name: 'martin'
    hosts: mis
  tasks:
    - name: Debian Family
      debug:
        msg: 'Family is Debian!'
      when: ansible_os_family == 'Debian'
      tags:
        - test
    - name: test connect
      ping: 
      tags:
        - test
    - name: ssh key auth
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
    - name: install tig package
      apt:
        name: tig
        state: latest       # [ installed | latest | removed | absent | present | build-dep ]
    - name: copy file to target hosts
      copy:
        src: ./files/hello.txt
        dest: /root/
      notify:               # only execute on the action state is changed
        - say hello
    - name: install docker package
      apt:
        name: docker.io
        state: present
    - name: start docker service
      service:
        name: docker
        state: stopped    # [ started | stopped | restarted | reloaded ]
        enabled: true
    - name: add user
      user:
        name: '{{ user_name }}'
        state: present    # [ present | absent]
        # groups: wheel,group2
        # remove: yes
        append: yes
        password: '$6$Oj0b5EbN$5rOHIh86hRFx70CUeVIzdDRgOhic8sKhLcj54VKdk/ogsqOeXulYywYI2YRE.EmRDdzMUifroh/x4GzmM1fuK.' # sha-512
      tags:
        - user



  handlers:
    - name: restart docker
      service: 
        name: docker
        state: restarted
    - name: say hello
      debug:
        msg: hello !
