---

- name: ansible playbook
  hosts: all
  gather_facts: false
  remote_user: root
  # become: yes
  tasks:
    - name: test connect
      ping: 
      tags:
        - test
    - name: ssh key auth
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
    - name: install tig package
      apt:
        name: tig
        state: latest       # [ installed | latest | removed | absent | present | build-dep ]
    - name: copy file to target hosts
      copy:
        src: ./files/hello.txt
        dest: /root/
      notify:               # only execute on the action state is changed
        - say hello
    - name: install docker package
      apt:
        name: docker.io
        state: present
    - name: start docker service
      service:
        name: docker
        state: stopped    # [ started | stopped | restarted | reloaded ]
        enabled: true
  handlers:
    - name: restart docker
      service: 
        name: docker
        state: restarted
    - name: say hello
      debug:
        msg: hello !
