---

- name: ansible palybook
  hosts: all
  remote_user: root
  # become: yes
  tasks:
    - name: test connect
      ping: 
    - name: ssh key auth
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
    - name: install tig package
      apt:
        name: tig
        state: latest       # install the latest version
        # state: removed    # remove the package
